### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by TobiasDeBruijn** [svsticky/chroma#20]
It looks like currently, albums aren't sorted when shown. This probably should be the case.

**Comment by TobiasDeBruijn** [comment]
Albums are now sorted chronologically.

**Comment by sam32123** [comment]
> Albums are now sorted chronologically.

on fotos.svsticky.nl, they are sorted newest to oldest (inverse chronologic I guess?). Wouldn't it be nicer if chroma also showed the albums newest to oldest? I think users want to look for the recent activities most times.
