### ISSUE TITLE
Generate thumbnails

### ISSUE THREAD

**Issue by Riscky** [svsticky/chroma#4]
`chroma`s predecessor, `pxl`, generates thumbnails for each uploaded picture, in two sizes:
- w1600 (1600 pixels wide)
- w400 (400 pixels wide)
The original picture is also be stored.
 
These different sizes are used in different locations on the photo website:
- w400 thumbnails is used for the album cover picture and the album overview
- w1600 is used for the lightbox (single picture view)
- The original size is served when people click the download button

I think `chroma` should also support thumbnails at some point, as this makes loading the website a lot quicker, especially when there are lots of pictures in the viewport.
Since we already have thumbnails in sizes w400 and w1600 in `pxl`, which we want to [migrate](https://github.com/svsticky/chroma/issues/3) over to `chroma` , we might as well use the same sizes in `chroma`.

I'm not sure if this is a requirement to start using `chroma` in production, but it might very well be if it turns out to be too slow. With 12 original sized pictures in the viewport, a client has to load about 24 Mb on each pageview, and there is no CDN that can make that feel fast.

Note that we can go three ways here: generating thumbnails on upload, generating thumbnails on request, and generating thumbnails as a background- or recurring job. I think the last option is the best, as this means uploads and downloads will be quick.

**Comment by TobiasDeBruijn** [comment]
3afb969 addresses this issue server, while not a full background job, the other qualities get created asynchronously on upload. I.e., the user does not have to wait for them to be generated.

All thats left to do, I think, is adding support for the other qualities in the web application.

**Comment by SilasPeters** [comment]
> With 12 original sized pictures in the viewport, a client has to load about 24 Mb on each pageview [...]

I am not quite aware to what extend this issue/feature has been addressed and implemented. However, I would just like to add that this estimation is quite optimistic, as with some (perhaps luxurious) camera settings, a single picture itself can be 24 Mb already. This feature might be more needed than expected.

**Comment by TobiasDeBruijn** [comment]
I've now fully implemented it in the frontend too.
Using the four supermentor images from this year's [Intro site](https://intro-cs.nl/), yields the following results:
- Original: ~27 MB
- New: ~825 kB

Note the ~, the requests do not include _only_ the pictures, also some metadata (but most if it is pictures).
